### ISSUE TITLE
Adding search field?

### ISSUE THREAD

**Issue by geekpete** [foundata/dokuwiki-template-prsnl10#2]
Hi,

Cool theme :)

How might I rig a search form on the front page using this theme?

**Comment by xrat** [comment]
I also wanted a search field. Here's my hack replacing the navigation header with `tpl_searchform()` which can be done by changing 1 line in `main.php`. The rest is CSS.

In `main.php` look for `<div id="tmpl_header_right">`. Within this `<div>` there is 1 line reading `echo $interim;` (currently, prsnl10 v2013-11-17, it's line 166). Comment out this line and add `tpl_searchform` as shown here:

``` php
// echo $interim; // search form hack
tpl_searchform(true,true);
```

The CSS code is of course much a matter of taste. The following should be a reasonable starting point:

``` css
form.search input.edit {width: 16em; padding: 0.35em 22px 0.35em 0.1em;}
.dokuwiki input.edit, .dokuwiki select.edit {vertical-align: middle;}
form.search input.edit {
        border: 1px solid rgb(204, 204, 204);
        box-shadow: 0px 0px 1px rgb(238, 238, 238)
        inset;
        border-radius: 2px 2px 2px 2px;
}
form.search input, button {
        font-style: inherit;
        font-size: 14px;
        font-size-adjust: inherit;
        font-stretch: inherit;
        font-weight: normal;
        color: rgb(51, 51, 51);background-color:rgb(255, 255, 255);
        line-height: 16px;
        margin: 0px;
        vertical-align:middle;
        -moz-box-sizing: border-box;
}

form.search input.button {
        background: url("https://www.dokuwiki.org/lib/tpl/dokuwiki/images/search.png") no-repeat scroll 0px 0px transparent;
        border-width: 0px;width: 19px;height: 14px;text-indent: -99999px;
        margin-left: -20px;box-shadow: none;padding: 0px;
}
form.search div.no { position: relative;z-index: 1; }
form.search div.ajax_qsearch {
        background-color: #efeeee;
   position: absolute; top: 47px;
        left: -11em;
        max-width: 28em;
        font-size: 13px;
        text-align: left;
        z-index: 20;
        display: none;
}
form.search div.ajax_qsearch a {
        text-transform: none !important;
}
/* Matching pagenames */
form.search div.ajax_qsearch strong {
        display: block;
        margin: .3em .3em .4em .2em;
}
```

You should replace `https://www.dokuwiki.org/lib/tpl/dokuwiki/images/search.png` with the URL and path of your own Wiki.
